"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var inversify_inject_decorators_1 = require("inversify-inject-decorators");
var inversify_1 = require("inversify");
require("reflect-metadata");
var BaseManager_1 = require("./manager/BaseManager");
var kernel = new inversify_1.Container();
exports.kernel = kernel;
kernel.bind(BaseManager_1.default).to(BaseManager_1.default).inSingletonScope();
var _a = inversify_inject_decorators_1.default(kernel), lazyInject = _a.lazyInject, lazyInjectNamed = _a.lazyInjectNamed, lazyInjectTagged = _a.lazyInjectTagged, lazyMultiInject = _a.lazyMultiInject;
exports.lazyInject = lazyInject;
exports.lazyInjectNamed = lazyInjectNamed;
exports.lazyInjectTagged = lazyInjectTagged;
exports.lazyMultiInject = lazyMultiInject;
